# Task 1


# Task 3 WS/Datastream
# --- Input: Pulled Data ---
worldscope_sample_save_path_csv: 'data/pulled/wrds_ws_stock.csv'
datastream_sample_save_path_csv: 'data/pulled/wrds_ds2dsf.csv'
link_ds_ws_save_path_csv: 'data/pulled/wrds_link_ds_ws.csv'

# --- Output: Prepared Data ---
prepared_data_save_path: 'data/generated/prepared_data.csv'
prepared_data_save_path_parquet: 'data/generated/prepared_data.parquet'