# Task 1


# Task 3 WS/Datastream
# --- Input: Pulled Data ---
worldscope_sample_save_path_csv: 'data/pulled/wrds_ws_stock.csv'
datastream_sample_save_path_csv: 'data/pulled/wrds_ds2dsf.csv'
link_ds_ws_save_path_csv: 'data/pulled/wrds_link_ds_ws.csv'

# --- Output: Generated Data ---
prepared_wrds_ds2dsf_path: 'data/generated/prepared_data_wrds_ds2dsf.csv'
prepared_wrds_ds2dsf_parquet: 'data/generated/prepared_data_wrds_ds2dsf.parquet'

bhr_output_csv: "data/generated/bhr_results.csv"
bhr_output_parquet: "data/generated/bhr_results.parquet"